root_dir: '/scratch/home/tsztank/sts-sequencing'
temp_dir: '/tmp'
microscopy_out: '/data/rajewsky/slideseq_microscopy/qc/'

external_bin:
    dropseq_tools: '/data/rajewsky/shared_bins/Drop-seq_tools-2.4.0'
    picard_tools: '/data/rajewsky/shared_bins/picard-tools-2.9.0/picard.jar'

puck_data:
    barcode_file: predictions_ml.csv

basecall_folders:
    - '/data/rajewsky/sequencing/nextSeqRaw'
    - '/data/remote/basecalls'

projects:
    #    - sample_sheet: /data/rajewsky/projects/slide_seq/sample_sheets/210329_NR_Sts_79.csv
    #      flowcell_id: 210329_NS500648_0564_AHGJLMBGXG
    # - sample_sheet: /scratch/home/tsztank/20191206_spatseq_smples3-4.csv
    #   flowcell_id: 191206_NS500648_0416_AHY3KYBGXC
    # - sample_sheet: /data/rajewsky/home/tsztank/200110_STS_017_4-7-8STS_018_1.csv
    #   flowcell_id: 200110_NS500648_0423_AHT5FHBGXC
    #    - sample_sheet: /data/rajewsky/projects/slide_seq/sample_sheets/210121_sts_067_1_3_5_Maria_organoids_C2_V2_sample_sheet.csv
    #      flowcell_id: 210121_NB501326_0478_AHGKCFBGXG

barcode_flavor: 
    dropseq: 'default'

    drop_noUMI:
        projects:
            - sts_079
    visium:
        projects:
            - cdr1as_ko_visium
    slideseq_14bc:
        samples:
            - slideseq_v2_mouse_hippo
            - slideseq_v2_e12

downstream_analysis_variables:
    default:
        expected_n_beads: 100000
        umi_cutoff: [100, 300]
        clean_dge: True
        plot_bead_size: 0.1
        plot_bead_border: False
    visium:
        expected_n_beads: 10000
        umi_cutoff: [500]
        clean_dge: False
        plot_bead_size: 1
        plot_bead_border: True
    less_beads:
        expected_n_beads: 60000
        umi_cutoff: [10, 20, 50, 100]
        clean_dge: True
    slideseq:
        expected_n_beads: 100000
        umi_cutoff: [100, 300]
        clean_dge: False
        plot_bead_size: 0.1
        plot_bead_border: False

additional_projects:
    - project_id: slideseq_v2
      sample_id: slideseq_v2_e12
      puck_id: Puck_190926_03
      species: mouse
      R1: /data/rajewsky/home/tsztank/projects/spatial/slideseqv2/raw_data/Puck_190926_03_R1.fastq.gz
      R2: /data/rajewsky/home/tsztank/projects/spatial/slideseqv2/raw_data/Puck_190926_03_R2.fastq.gz
      downstream_analysis_type: 'slideseq'
    - project_id: slideseq_v2
      sample_id: slideseq_v2_mouse_hippo
      puck_id: Puck_200115_08
      species: mouse
      R1: /data/rajewsky/home/tsztank/projects/spatial/slideseqv2/raw_data/Puck_200115_08_R1.fastq.gz
      R2: /data/rajewsky/home/tsztank/projects/spatial/slideseqv2/raw_data/Puck_200115_08_R2.fastq.gz
      puck_barcode_file: /data/rajewsky/home/tsztank/projects/spatial/slideseqv2/Puck_200115_08_bead_locations.csv
      downstream_analysis_type: 'slideseq'
    - project_id: cdr1as_ko_visium
      sample_id: cdr1as_ko_visium_wt_1
      puck_id: NoOptical
      species: mouse
      R1: /data/rajewsky/projects/cdr1as_ko_visium/data/reads/linked/wt_1_S3_L002_R1_001.fastq.gz
      R2: /data/rajewsky/projects/cdr1as_ko_visium/data/reads/linked/wt_1_S3_L002_R2_001.fastq.gz
      downstream_analysis_type: 'visium'
      puck_barcode_file: /data/rajewsky/home/tsztank/projects/spatial/repos/sts-sequencing/visium_barcode_positions.csv

# downsample and saturation analysis
downsample: 
    projects:
        - cdr1as_ko_visium
        - slideseq_v2
    samples:
        - cdr1as_ko_visium_wt_1

# in the output each will have an merged_ prepended to their root directory
# samples_to_merge:`

adapters:
    smart: 'AAGCAGTGGTATCAACGCAGAGTGAATGGG'
    optical_primer: 'GAATCACGATACGTACACCA'

knowledge:
    annotations:
        human: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/gencode.v32.primary_assembly.annotation.gtf
        mouse: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/gencode.vM23.primary_assembly.annotation.gtf
    genomes:
        human: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/GRCh38.primary_assembly.genome.fa
        mouse: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/GRCm38.primary_assembly.genome.fa
    indices:
        human:
            star: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/STAR_index
        mouse:
            star: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/STAR_index
            bt2_rRNA: /data/rajewsky/indices/mm10_rRNA_bowtie2_2.3.3.1/mouse_rRNA

    barcode_flavor:
        dropseq:
            cell: "r1[8:20][::-1]"
            UMI: "r1[0:8]"
            bam_tags: "CR:{cell},CB:{cell},MI:{UMI},RG:{assigned}"
        slideseq_14bc:
            cell: "r1[0:14]"
            UMI: "r1[14:23]"
            bam_tags: "CR:{cell},XC:{cell},XM:{UMI},RG:{assigned}"
        slideseq_15bc:
            cell: "r1[0:14]"
            UMI: "r1[15:23]"
            bam_tags: "CR:{cell},XC:{cell},XM:{UMI},RG:{assigned}"
        drop_noUMI:
            cell: "r1[0:12][::-1]"
            UMI: "r2[0:8]"
            bam_tags: "CR:{cell},CB:{cell},MI:{UMI},RG:{assigned}"
        visium:
            cell: "r1[0:16]"
            UMI: "r1[16:28]"
            bam_tags: "CR:{cell},CB:{cell},MI:{UMI},RG:{assigned}"
