root_dir: '/data/rajewsky/projects/slide_seq'
microscopy_root: '/data/rajewsky/slideseq_microscopy'
bin_dir: '/data/rajewsky/shared_bins'
temp_dir: '/tmp'

illumina_projects:
    # - sample_sheet: /scratch/home/tsztank/20191206_spatseq_smples3-4.csv
    #   flowcell_id: 191206_NS500648_0416_AHY3KYBGXC
    # - sample_sheet: /data/rajewsky/home/tsztank/200110_STS_017_4-7-8STS_018_1.csv
    #   flowcell_id: 200110_NS500648_0423_AHT5FHBGXC
    - sample_sheet: /data/rajewsky/projects/slide_seq/sample_sheets/210121_sts_067_1_3_5_Maria_organoids_C2_V2_sample_sheet.csv
      flowcell_id: 210121_NB501326_0478_AHGKCFBGXG

barcode_flavor: 
    dropseq: 'default'

    drop_noUMI:
        projects:
            - sts_058
            - sts_070
            - test_030
        samples:
            - sts_053_1
            - sts_067_1
            - sts_067_1_reseq
            - sts_067_1_reseq2
            - maria_organoids_ctrl_3
            - maria_organoids_ctrl_5

    comb1:
        projects:
            - sts_067

additional_illumina_projects:
    - project_id: test_030
      sample_id: test_030_4
      puck_id: NoOptical
      species: mouse
      R1: /data/rajewsky/projects/slide_seq/raw_data/test_data/test_030_4_R1.fastq.gz
      R2: /data/rajewsky/projects/slide_seq/raw_data/test_data/test_030_4_R2.fastq.gz

# downsample and saturation analysis
downsample: 
    projects:
    samples:

# in the output each will have an merged_ prepended to their root directory
# samples_to_merge:`

adapters:
    smart: 'AAGCAGTGGTATCAACGCAGAGTGAATGGG'

knowledge:
    annotations:
        human: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/gencode.v32.primary_assembly.annotation.gtf
        mouse: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/gencode.vM23.primary_assembly.annotation.gtf
        ercc: /data/rajewsky/home/nkarais/ercc_STAR_2.7.1a/ERCC92.gtf
        erccgfp: /data/rajewsky/home/nkarais/ercc_gfp_STAR_2.7.1a/ercc_gfp.gtf
        celegans: /data/rajewsky/annotation/filippos_sucks/ce11/ce11_filtered.gtf
        humancelegans: /data/rajewsky/home/nkarais/hg38_GRCh38.84_ce11_STAR_2.7.1a/MegaAnnotation.gtf

    genomes:
        human: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/GRCh38.primary_assembly.genome.fa
        mouse: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/GRCm38.primary_assembly.genome.fa
        ercc: /data/rajewsky/home/nkarais/ercc_STAR_2.7.1a/ERCC92.fa
        erccgfp: /data/rajewsky/home/nkarais/ercc_gfp_STAR_2.7.1a/ercc_gfp.fa
        celegans: /data/rajewsky/genomes/ce11_public/ce11.fa
        humancelegans: /data/rajewsky/home/nkarais/hg38_GRCh38.84_ce11_STAR_2.7.1a/MegaGenome.fa

    indices:
        human:
            star: /data/rajewsky/home/nkarais/hg38_GRCh38_gencode.v32_STAR_2.7.1a/STAR_index
            bt2: /data/local/rajewsky/indices/hg38_GRCh38_gencode.v32_bowtie2.3.5.1/hg38_GRCh38_bt2_index
            bt2_rRNA: /data/rajewsky/indices/hsa_rrna_ncbi_bowtie_2.3.2/hsa_rrna_ncbi 
        mouse:
            star: /data/rajewsky/home/nkarais/mm10_GRCm38.p5_gencode.vM23_STAR_2.7.1a/STAR_index
            bt2: /data/local/rajewsky/indices/mm10_GRCm38.p5_gencode.vM23_bowtie2.3.5.1/mm10_GRCm38_bt2_index
            bt2_rRNA: /data/rajewsky/indices/mm10_rRNA_bowtie2_2.3.3.1/mouse_rRNA
        ercc:
            star: /data/rajewsky/home/nkarais/ercc_STAR_2.7.1a/STAR_index
        erccgfp:
            star: /data/rajewsky/home/nkarais/ercc_gfp_STAR_2.7.1a/STAR_index
            bt2: /data/local/rajewsky/indices/erccgfp_bowtie2.3.5.1/erccgfp_bt2_index
        celegans:
            star: /data/rajewsky/indices/ce11_star_2.7.1a
        humancelegans:
            star: /data/rajewsky/home/nkarais/hg38_GRCh38.84_ce11_STAR_2.7.1a/STAR_index

    barcode_flavor:
        dropseq:
            cell_bc: "r1[8:20][::-1]"
            UMI: "r1[0:8]"
        drop_noUMI:
            cell_bc: "r1[0:12][::-1]"
            UMI: "r2[0:8]"
        comb1:
            segments: 2
            bc1_ref: "/data/rajewsky/projects/combbeads/two_segments/illumina/index_BC1_96.fa"
            bc2_ref: "/data/rajewsky/projects/combbeads/two_segments/illumina/index_BC2_96_var.fa"
            bc1_cache: "/data/rajewsky/projects/combbeads/two_segments/illumina/bc1_cache.tsv"
            bc2_cache: "/data/rajewsky/projects/combbeads/two_segments/illumina/bc2_cache.tsv"
            score_threshold: 0.5
            cell_bc: "bc1[-6:][::-1]+bc2[-6:][::-1]"
            UMI: "r2[0:8]"

