illumina_runs:
    test:
        samplesheet: /scratch/home/tsztank/spatial_pipeline/test/20191206_spatseq_smples3-4.csv
        flowcell_id: 191206_NS500648_0416_AHY3KYBGXC
#    test2:
#        samplesheet: /scratch/home/tsztank/spatial_pipeline/test2/20191206_spatseq_smples3-4.csv
#        flowcell_id: 191206_NS500648_0416_AHY3KYBGXC

adapters:
    smart: 'AAGCAGTGGTATCAACGCAGAGTGAATGGG'
